name: Build
on: 
  - push:
  - pull_request:
  - paths-ignore:
    - 'README*'
    - 'LICENSE*'
    - '.github/workflows/build.yml'
    - '.github/workflows/update_maven_wrapper.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
